require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Style/LambdaCall:
  EnforcedStyle: braces

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Style/NestedParenthesizedCalls:
  AllowedMethods:
    - be
    - be_a
    - be_an
    - be_between
    - be_falsey
    - be_kind_of
    - be_instance_of
    - be_truthy
    - be_within
    - eq
    - eql
    - end_with
    - expect
    - include
    - match
    - raise_error
    - respond_to
    - start_with

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/BlockLength:
  IgnoredMethods:
    - define_formatter_for
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/EachWithObject:
  Enabled: false


